=== xiaochun-yang/19-ID/logging/src/logsystem.dtd
<!-- DTD used by the java.util.logging.LogManager -->
<!-- This provides an XML formatted logger configuration. -->

<!-- The document type is "logsystem" which consists of a list of logger elements -->
<!ELEMENT logsystem (logger*)>

<!-- Each logger has arbitrary attributes, a list of handlers and formatters -->
<!ELEMENT logger (property*, formatter*, handler*)>
<!ATTLIST logger name CDATA #required>
<!ATTLIST logger parent CDATA #required>
<!ATTLIST logger level CDATA #required>

<!-- Each property is an empty element with name and type as attributes -->
<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #required>
<!ATTLIST property value CDATA #required>

<!-- Each formatter has name, type as attributes and a list 
     arbitary properties as sub elements -->
<!ELEMENT formatter (name, type, property*)>
<!ATTLIST formatter name CDATA #required>
<!ATTLIST formatter type (simple|xml) #required>

<!-- Each handler has name, type as attributes and a list 
     arbitary properties as sub elements -->
<!ELEMENT handler (name, type, property*)>
<!ATTLIST handler name CDATA #required>
<!ATTLIST handler type (console|file) #required>
<!ATTLIST handler level (OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL) #required>
<!ATTLIST handler filter CDATA #required>
<!ATTLIST handler formatter CADATA #required>

=== xiaochun-yang/19-ID/logging/src/logsystem.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE logsystem SYSTEM "logsystem.dtd">
<logsystem>
<logger name="aa" parent="" level="ALL"/>
  <formatter name="xml_formatter" type="xml">
  </formatter>
  <formatter name="simple_formatter" type="simple">
	<property name="pattern" value="%m [%p,%t]: %s"/>
  </formatter>
  <handler name="file_handler" type="file" level="ALL" filter="" formatter="xml_formatter">
	<property name="pattern" value="c:\\temp\\log_%g.%u.log"/>
	<property name="is_append" value="false"/>
	<property name="max_size" value="5000"/>
	<property name="num_files" value="50"/>
  </handler>
  <handler name="console_handler" type="console" level="SEVERE" filter="" formatter="simple_formatter>
  </handler>
</logger>
</logsystem>
